### ISSUE TITLE
Export HPO output to fill Phenogenius App

### ISSUE THREAD

**Issue by thomasguignard** [kyauy/Linguo-Franca#2]
Hello,
It would be so nice if the HPO output could fill the phenogenius form (https://phenogenius.streamlit.app/).

**Comment by kyauy** [comment]
Sure, others asks for this feature, I definitely will implement this :)

**Comment by kyauy** [comment]
This is done, phenogenius now can take 2 inputs (interactive selection and list of HPO terms separated by comma).
Linguo Franca now provides this output :)
